### ISSUE TITLE
USB 3 Adapter Gerber / Layout file

### ISSUE THREAD

**Issue by redex557** [xtrx-sdr/xtrx-docs#5]
According to product descriptions found on the internet the XTRX USB3 adapter seems to be open hardware. As you published the schematics in this repo it seems about right. Could you upload the matching pcb layout files or gerbers? I would like to build my own adapter board as it's impossible to find one nowadays. 

> The XTRX hardware itself is proprietary, though the hardware accessories we designed for it (e.g., the USB 3 and PCIe adapters) are open hardware.

**Comment by redex557** [comment]
@earwin @chemeris @sergforce anyone still here?

**Comment by earwin** [comment]
I am, but I don't have access, sorry.

**Comment by redex557** [comment]
Thanks for the fast reply! Do you think you could try to contact someone with access? 
I really would like to use my xtrx with a USB adapter...

**Comment by earwin** [comment]
I got you the files, need to sort through, will publish in a few days.

**Comment by oldrandomstranger** [comment]
will you publish the matching pcb files for PCIe x2 adapter?

**Comment by earwin** [comment]
Let me see about pcie x2+fe. usb3 files export is being vetted right now.

**Comment by earwin** [comment]
@redex557 @oldrandomstranger: Please, see https://github.com/xtrx-sdr/xtrx-adapters for pcb files

**Comment by redex557** [comment]
@earwin Thanks a lot!
